### ISSUE TITLE
Image flashing, while navigating different sections of app

### ISSUE THREAD

**Issue by danielappelgren0** [Baseflow/flutter_cached_network_image#415]
### Expected behavior

Images should be loaded and saved in some cache after initial load, and therefor not cause the image to flash on second. visit.

### Reproduction steps

Load some images that uses the CachedNetworkImage -> Navigate different sections of app and go back.

### Configuration

**Version:** 2.2.0+1

**Platform:** 
- [X] :iphone: iOS
- [X] :robot: Android

**Comment by danielappelgren0** [comment]
If you need more information for how to reproduce let me know i can provide some :)

**Comment by renefloor** [comment]
Could you test this with 2.3.0-beta.1+1? This issue is one of the things that should be fixed in that beta.

**Comment by danielappelgren0** [comment]
Just to be sure, it's not the Flutter beta branch you mean. I just tested that, and the issue is still there :) If there is a beta version of the plugin available how do i use that instead ? :)

**Comment by danielappelgren0** [comment]
Thanks for letting me know about the beta version. I just tested this and is it works great. I just got this issue while switching tabs with different images: 

I/flutter ( 3677): 14:45:47.215 [fatal]    Flutter error
I/flutter ( 3677): {context: when reporting an error to an image listener, library: image resource service, installationId: 36b9c99687404cd8bc70266d04de221e, route: /, previousRoute: /store/5a33acba817a401d845155bdc737b2e9/feed}
I/flutter ( 3677): setState() called after dispose(): _ImageState#f4ddd(lifecycle state: defunct, not mounted, stream: ImageStream#52034(MultiFrameImageStreamCompleter#9b14b, [1200×1544] @ 1.0x, 1 listener), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)
I/flutter ( 3677): This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
I/flutter ( 3677): The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
I/flutter ( 3677): This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the ref
I/flutter ( 3677): <flutter>
I/flutter ( 3677): <asynchronous suspension>
I/flutter ( 3677): <flutter>
I/flutter ( 3677): <dart>
I/flutter ( 3677): #22     CachedNetworkImageProvider._loadAsync (package:cached_network_image/src/image_provider/_image_provider_io.dart)
I/flutter ( 3677): <asynchronous suspension>
I/flutter ( 3677): #23     CachedNetworkImageProvider.load (package:cached_network_image/src/image_provider/_image_provider_io.dart:54:14)
I/flutter ( 3677): <flutter>
I/flutter ( 3677): <dart>
I/flutter ( 3677): <flutter>
I/flutter ( 3677): <dart>

**Comment by renefloor** [comment]
Thanks for testing.
That issue is the same as what causes this: https://github.com/Baseflow/flutter_cached_network_image/issues/400

The fix for this in Flutter is just released on the beta channel, so if you switch to the beta channel this should be fixed.
You have to determine for yourself if switching to the Flutter beta channel is worth it to fix the flashing.

**Comment by danielappelgren0** [comment]
Thanks for the answers i'll close this now :)
