### ISSUE TITLE
MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)

### ISSUE THREAD

**Issue by thanhhuan1990** [Baseflow/flutter_cached_network_image#439]
### Crash log
`6621-6873 E: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
    #2      MethodChannelPathProvider.getTemporaryPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:34:26)
    #3      getTemporaryDirectory (package:path_provider/path_provider.dart:60:39)
    #4      DefaultCacheManager.getFilePath (package:flutter_cache_manager/src/cache_manager.dart:44:27)
    #5      BaseCacheManager._createFileDir (package:flutter_cache_manager/src/cache_manager.dart:254:41)
    #6      BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:23)
    #7      new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
    #8      new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
    #9      new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
    #10     CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:404:35)
    #11     CachedNetworkImageState._createFileStream (package:cached_network_image/src/cached_image_widget.dart:242:19)
    #12     CachedNetworkImageState.initState (package:cached_network_image/src/cached_image_widget.dart:219:5)
    #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
    #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
    #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #19     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
    #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
    #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #24     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #26     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #35     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
    #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #39     _InheritedProviderScopeElement.performRebuild (package:provider/src/inherited_provider.dart:397:11)
    #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #42     Compon
6621-6873 E: [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
    #2      invokeMethod (package:sqflite/src/sqflite_impl.dart:17:13)
    #3      SqfliteDatabaseFactoryImpl.invokeMethod (package:sqflite/src/factory_impl.dart:82:7)
    #4      SqfliteDatabaseFactoryMixin.safeInvokeMethod.<anonymous closure> (package:sqflite_common/src/factory_mixin.dart:25:35)
    #5      wrapDatabaseException (package:sqflite/src/exception_impl.dart:7:32)
    #6      SqfliteDatabaseFactoryImpl.wrapDatabaseException (package:sqflite/src/factory_impl.dart:78:7)
    #7      SqfliteDatabaseFactoryMixin.safeInvokeMethod (package:sqflite_common/src/factory_mixin.dart:25:7)
    #8      SqfliteDatabaseFactoryMixin.getDatabasesPath (package:sqflite_common/src/factory_mixin.dart:143:26)
    #9      getDatabasesPath (package:sqflite/sqflite.dart:168:54)
    #10     CacheStore._getObjectProvider (package:flutter_cache_manager/src/cache_store.dart:43:33)
    #11     new CacheStore (package:flutter_cache_manager/src/cache_store.dart:39:49)
    #12     BaseCacheManager._createCacheStore (package:flutter_cache_manager/src/cache_manager.dart:263:12)
    #13     new BaseCacheManager (package:flutter_cache_manager/src/cache_manager.dart:84:28)
    #14     new DefaultCacheManager._ (package:flutter_cache_manager/src/cache_manager.dart:40:29)
    #15     new DefaultCacheManager (package:flutter_cache_manager/src/cache_manager.dart:36:39)
    #16     CachedNetworkImageState._cacheManager (package:cached_network_image/src/cached_image_widget.dart:404:35)
    #17     CachedNetworkImageState._createFileStream (package:cached_network_image/src/cached_image_widget.dart:242:19)
    #18     CachedNetworkImageState.initState (package:cached_network_image/src/cached_image_widget.dart:219:5)
    #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
    #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
    #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #25     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5991:32)
    #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
    #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
    #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
    #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
    #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
    #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
    #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
    #41     SingleChildWidgetElementMixin.mount (package:nested/nested.dart:223:11)
    #42     Element.inflateWidget (package:flutter/src/widgets/`

**Version:** 2.2.0+1

### Flutter doctor -v
`[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.5 19F101, locale en-VN)
    • Flutter version 1.20.1 at /Users/jakehuynh/flutter
    • Framework revision 2ae34518b8 (3 days ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jakehuynh/Library/Android/sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6494.35

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
`

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by thanhhuan1990** [comment]
This issue is fixed by upgrades to Android V2

**Comment by omaralmgerbie** [comment]
hey I migrated to android V2 but I'm still having the same issue
