### ISSUE TITLE
Bad state: Cannot clone a disposed image

### ISSUE THREAD

**Issue by masewo** [Baseflow/flutter_cached_network_image#513]
## 🔙 Regression

When trying to load the same image on another page I get following error and the image is not shown:

```
I/flutter (16942): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (16942): The following StateError was thrown by a synchronously-called image listener:
I/flutter (16942): Bad state: Cannot clone a disposed image.
I/flutter (16942): The clone() method of a previously-disposed Image was called. Once an Image object has been
I/flutter (16942): disposed, it can no longer be used to create handles, as the underlying data may have been released.
I/flutter (16942): 
I/flutter (16942): When the exception was thrown, this was the stack:
I/flutter (16942): #0      Image.clone (dart:ui/painting.dart:1758:7)
I/flutter (16942): #1      ImageInfo.clone (package:flutter/src/painting/image_stream.dart:51:20)
I/flutter (16942): #2      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:493:41)
I/flutter (16942): #3      MultiImageStreamCompleter.addListener (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:168:11)
I/flutter (16942): #4      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:356:26)
I/flutter (16942): #5      _ImageState._listenToStream (package:flutter/src/widgets/image.dart:1240:19)
I/flutter (16942): #6      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1113:7)
I/flutter (16942): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4833:11)
I/flutter (16942): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
I/flutter (16942): ...     Normal element mounting (76 frames)
I/flutter (16942): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
I/flutter (16942): #85     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6282:32)
I/flutter (16942): ...     Normal element mounting (10 frames)
I/flutter (16942): #95     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
I/flutter (16942): #96     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6282:32)
I/flutter (16942): ...     Normal element mounting (4 frames)
I/flutter (16942): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
I/flutter (16942): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:3380:18)
I/flutter (16942): #102    _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:136:18)
I/flutter (16942): #103    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:19)
I/flutter (16942): #104    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:118:12)
I/flutter (16942): #105    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1883:59)
I/flutter (16942): #106    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
I/flutter (16942): #107    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1883:14)
I/flutter (16942): #108    RenderConstrainedLayoutBuilder.rebuildIfNecessary (package:flutter/src/widgets/layout_builder.dart:225:7)
I/flutter (16942): #109    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:351:5)
I/flutter (16942): #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #111    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:565:15)
I/flutter (16942): #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #118    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1306:11)
I/flutter (16942): #119    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #120    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #121    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #122    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #123    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #124    RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:246:12)
I/flutter (16942): #125    RenderSliverPinnedPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:430:5)
I/flutter (16942): #126    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #127    RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:508:13)
I/flutter (16942): #128    RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1566:12)
I/flutter (16942): #129    RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1475:20)
I/flutter (16942): #130    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #131    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #132    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #133    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #134    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #135    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #136    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #137    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #138    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #139    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #140    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #141    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #142    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #143    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #144    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #145    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #146    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #147    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #148    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #149    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:208:12)
I/flutter (16942): #150    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #151    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
I/flutter (16942): #152    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:911:7)
I/flutter (16942): #153    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
I/flutter (16942): #154    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
I/flutter (16942): #155    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #156    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #157    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #158    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #159    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1306:11)
I/flutter (16942): #160    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #161    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #162    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #163    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #164    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #165    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #166    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #167    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #168    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #169    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #170    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #171    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #172    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #173    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #174    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #175    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:14)
I/flutter (16942): #176    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #177    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #178    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #179    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
I/flutter (16942): #180    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (16942): #181    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (16942): #182    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:454:19)
I/flutter (16942): #183    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:895:13)
I/flutter (16942): #184    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
I/flutter (16942): #185    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (16942): #186    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (16942): #187    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (16942): #191    _invoke (dart:ui/hooks.dart:157:10)
I/flutter (16942): #192    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
I/flutter (16942): #193    _drawFrame (dart:ui/hooks.dart:120:31)
I/flutter (16942): (elided 3 frames from dart:async)
I/flutter (16942): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16942): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (16942): The following StateError was thrown by a synchronously-called image listener:
I/flutter (16942): Bad state: Cannot clone a disposed image.
I/flutter (16942): The clone() method of a previously-disposed Image was called. Once an Image object has been
I/flutter (16942): disposed, it can no longer be used to create handles, as the underlying data may have been released.
I/flutter (16942): 
I/flutter (16942): When the exception was thrown, this was the stack:
I/flutter (16942): #0      Image.clone (dart:ui/painting.dart:1758:7)
I/flutter (16942): #1      ImageInfo.clone (package:flutter/src/painting/image_stream.dart:51:20)
I/flutter (16942): #2      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:493:41)
I/flutter (16942): #3      MultiImageStreamCompleter.addListener (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:168:11)
I/flutter (16942): #4      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:356:26)
I/flutter (16942): #5      _ImageState._listenToStream (package:flutter/src/widgets/image.dart:1240:19)
I/flutter (16942): #6      _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:1113:7)
I/flutter (16942): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4833:11)
I/flutter (16942): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4649:5)
I/flutter (16942): ...     Normal element mounting (21 frames)
I/flutter (16942): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
I/flutter (16942): #30     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6282:32)
I/flutter (16942): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
I/flutter (16942): #32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6282:32)
I/flutter (16942): ...     Normal element mounting (36 frames)
I/flutter (16942): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3615:14)
I/flutter (16942): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3380:18)
I/flutter (16942): #70     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1229:37)
I/flutter (16942): #71     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1214:20)
I/flutter (16942): #72     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:19)
I/flutter (16942): #73     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1207:12)
I/flutter (16942): #74     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:350:23)

════════ Exception caught by image resource service ════════════════════════════════════════════════
The following StateError was thrown by a synchronously-called image listener:
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.

When the exception was thrown, this was the stack: 
#0      Image.clone (dart:ui/painting.dart:1758:7)
#1      ImageInfo.clone (package:flutter/src/painting/image_stream.dart:51:20)
#2      ImageStreamCompleter.addListener (package:flutter/src/painting/image_stream.dart:493:41)
#3      MultiImageStreamCompleter.addListener (package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:168:11)
#4      ImageStream.addListener (package:flutter/src/painting/image_stream.dart:356:26)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by image resource service ════════════════════════════════════════════════
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16942): #75     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1883:59)
I/flutter (16942): #76     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:915:15)
I/flutter (16942): #77     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1883:14)
I/flutter (16942): #78     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:339:5)
I/flutter (16942): #79     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:485:5)
I/flutter (16942): #80     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:239:19)
I/flutter (16942): #81     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:282:19)
I/flutter (16942): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #83     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:139:12)
I/flutter (16942): #84     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:373:11)
I/flutter (16942): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #86     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:508:13)
I/flutter (16942): #87     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1566:12)
I/flutter (16942): #88     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1475:20)
I/flutter (16942): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #90     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #108    RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:208:12)
I/flutter (16942): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #110    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
I/flutter (16942): #111    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:911:7)
I/flutter (16942): #112    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
I/flutter (16942): #113    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
I/flutter (16942): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #118    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1306:11)
I/flutter (16942): #119    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #120    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #121    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #122    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #123    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #124    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #125    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #126    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #127    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #128    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #129    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #130    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #132    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #133    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #134    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3228:14)
I/flutter (16942): #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:14)
I/flutter (16942): #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
I/flutter (16942): #138    _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:743:15)
I/flutter (16942): #139    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (16942): #140    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:884:18)
I/flutter (16942): #141    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:454:19)
I/flutter (16942): #142    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:895:13)
I/flutter (16942): #143    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:320:5)
I/flutter (16942): #144    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (16942): #145    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (16942): #146    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (16942): #150    _invoke (dart:ui/hooks.dart:157:10)
I/flutter (16942): #151    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:253:5)
I/flutter (16942): #152    _drawFrame (dart:ui/hooks.dart:120:31)
I/flutter (16942): (elided 3 frames from dart:async)
I/flutter (16942): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### Old (and correct) behavior

Image gets loaded.

### Current behavior

Image gets not loaded with exception thrown.

### Configuration

**Version:** 2.4.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by M0E91** [comment]
+1 got exactly the same behavior since updating to the newest firebase dependencies and running a flutter packages upgrade

**Comment by tim-smart** [comment]
Looks like this is the related change:
https://github.com/Baseflow/flutter_cached_network_image/compare/v2.3.3...v2.4.0#diff-9c6cd047fac25d38850fe45171df90f53549781f1a0bb5486a1d53b6d5f24907R146

**Comment by renefloor** [comment]
Thanks and sorry. Fixed in 2.4.1.

**Comment by blaueeiner** [comment]
@renefloor This problem is still present on 2.4.1 and current version 2.5.0 for me. Specifically when doing a Navigator.of(context).pop() the exception is being triggered.

**Comment by renefloor** [comment]
@blaueeiner can you create a small reproducible example?

**Comment by fryette** [comment]
@renefloor 

Minimal reproducible sample with OctoImage

On the latest beta channel.

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:octo_image/octo_image.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int index = 0;

  @override
  void initState() {
    super.initState();
    Timer.periodic(
      Duration(seconds: 2),
      (timer) {
        setState(() {
          ++index;
        });
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: OctoImage(
        image:
            NetworkImage('https://via.placeholder.com/300.png/09f/fff?index=$index'),
        imageBuilder: (_, image) => image,
        placeholderBuilder: (_) => Container(color: Colors.red),
        gaplessPlayback: true,
      ),
    );
  }
}

```

[✓] Flutter (Channel beta, 1.26.0-17.6.pre, on macOS 11.2.1 20D75 darwin-x64, locale en)
    • Flutter version 1.26.0-17.6.pre at /Users/yauhen_sampir/fvm/versions/beta
    • Framework revision a29104a69b (9 days ago), 2021-02-16 09:26:56 -0800
    • Engine revision 21fa8bb99e
    • Dart version 2.12.0 (build 2.12.0-259.12.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/yauhen_sampir/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (2 available)
    • iPhone SE (2nd generation) (mobile) • E9B73389-701B-4946-AF0E-5ED9DC4DD01A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4
      (simulator)
    • Chrome (web)                        • chrome                               • web-javascript • Google Chrome 87.0.4280.88

**Comment by renefloor** [comment]
Process tracked in Baseflow/octo_image#17

**Comment by alexmarkley** [comment]
I'm also getting `Bad state: Cannot clone a disposed image`. However, in my case, I'm getting it upon device rotation.

```
════════ Exception caught by widgets library ═══════════════════════════════════
Bad state: Cannot clone a disposed image.
The clone() method of a previously-disposed Image was called. Once an Image object has been disposed, it can no longer be used to create handles, as the underlying data may have been released.
The relevant error-causing widget was
CachedNetworkImage
lib/…/misc/RCNetworkImage.dart:45
════════════════════════════════════════════════════════════════════════════════
```

In my case, my `imageUrl` will probably be changing after the device has rotated, because I pass the required image dimensions as a URL query parameter, so the server-side can respond with the best available version of the image.

Sorry if this is a different / unrelated issue to the above. Also, please let me know what other information I can provide for troubleshooting purposes.

Thanks!

**Comment by alexmarkley** [comment]
Thanks @renefloor for fixing this! I can confirm `cached_network_image` v3.0.0 fixes this issue for me.
