### ISSUE TITLE
App Crashes on Flutter 3.3

### ISSUE THREAD

**Issue by josh-burton** [Baseflow/flutter_cached_network_image#772]
## 🐛 Bug Report

When using CachedNetworkImage with Flutter 3.3, my app crashes on release builds.

I'm guessing this is related to the changes around [ImageProvider.loadBuffer](https://docs.flutter.dev/release/breaking-changes/image-provider-load-buffer).

### Expected behavior

The app doesn't crash.

### Reproduction steps

Use cached network image to load images. If more than 2 images are loaded in a listview, the app crashes.

```
CachedNetworkImage(
                    imageUrl: url,
                    fit: BoxFit.cover,
                  )
```

### Configuration

**Version:** 3.2.1

**Platform:** 
- [x]  :iphone: iOS
- [x] :robot: Android

<details>
  <summary>Full Crash Log (Android)</summary>
  
```
A/libc: Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x4cf003d0132 in tid 27436 (1.ui), pid 27374 (com.myapp)
A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG: Build fingerprint: ''
A/DEBUG: Revision: 'MP1.0'
A/DEBUG: ABI: 'arm64'
A/DEBUG: Timestamp: 2022-08-31 07:27:33.333060338+1200
A/DEBUG: Process uptime: 17s
A/DEBUG: Cmdline: com.myapp
A/DEBUG: pid: 27374, tid: 27436, name: 1.ui  >>> com.myapp <<<
A/DEBUG: uid: 10408
A/DEBUG: tagged_addr_ctrl: 0000000000000001 (PR_TAGGED_ADDR_ENABLE)
A/DEBUG: signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x000004cf003d0132
A/DEBUG:     x0  0000007a00008041  x1  0000007a0166d6a9  x2  000004cf003d0132  x3  0000007a0166d6b8
A/DEBUG:     x4  0000007a00009ae1  x5  0000007a0167fff8  x6  0000000000000000  x7  0000007a00008061
A/DEBUG:     x8  0000007be05d6138  x9  0000000000000000  x10 b400007da3348580  x11 0000000000000001
A/DEBUG:     x12 0000000000000001  x13 b400007d8334d4e0  x14 0000007a00000000  x15 0000007be5a568c8
A/DEBUG:     x16 0000007a00008041  x17 0000000000000008  x18 0000007be5496000  x19 0000007be05d611c
A/DEBUG:     x20 0000007be5a569e0  x21 b400007bc63efcf0  x22 0000007a00008041  x23 0000007be5a568d0
A/DEBUG:     x24 0000007be5a56a10  x25 0000000000000001  x26 b400007dd32d9760  x27 0000007a00b00040
A/DEBUG:     x28 000000080000007a  x29 0000007be5a569e0
A/DEBUG:     lr  0000007be0b86af8  sp  0000007be597d000  pc  000004cf003d0132  pst 0000000060001000
A/DEBUG: backtrace:
A/DEBUG:       #00 pc 000004cf003d0132  <unknown>
A/DEBUG:       #01 pc 0000000000941af4  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #02 pc 0000000000a212e4  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #03 pc 000000000039c9f4  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #04 pc 000000000039cb64  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #05 pc 000000000039c560  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #06 pc 000000000039c214  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #07 pc 000000000039ac40  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #08 pc 000000000039dc84  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #09 pc 0000000000942484  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #10 pc 00000000009423e8  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #11 pc 000000000039c9f4  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #12 pc 000000000039cb64  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #13 pc 000000000095d81c  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #14 pc 000000000096754c  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #15 pc 0000000000919d48  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #16 pc 000000000039d498  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #17 pc 000000000039d5f0  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #18 pc 000000000039d424  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #19 pc 000000000039cf80  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #20 pc 000000000039abb0  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #21 pc 000000000039a4f0  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #22 pc 0000000000a1ffa8  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #23 pc 0000000000a20268  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #24 pc 0000000000941b84  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #25 pc 0000000000a20498  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #26 pc 0000000000a25354  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #27 pc 0000000000941ff8  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #28 pc 0000000000941f80  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #29 pc 000000000039d498  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #30 pc 000000000039d5f0  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #31 pc 000000000095ce74  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #32 pc 00000000009643a8  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #33 pc 000000000095c5a4  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #34 pc 000000000039d4f8  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #35 pc 000000000039d5f0  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #36 pc 000000000095ce74  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #37 pc 00000000009643a8  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #38 pc 000000000095c5a4  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #39 pc 000000000039a2ec  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #40 pc 000000000039a1d0  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #41 pc 000000000039a194  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #42 pc 000000000038ed7c  /data/app/com.myapp/lib/arm64/libapp.so (BuildId: buildid)
A/DEBUG:       #43 pc 00000000006cb954  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #44 pc 00000000006cc764  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #45 pc 0000000000804e88  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #46 pc 00000000005b3e6c  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #47 pc 00000000003460b4  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #48 pc 0000000000349568  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #49 pc 0000000000011178  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+808) (BuildId: buildid)
A/DEBUG:       #50 pc 00000000000185e4  /system/lib64/libandroid.so (ALooper_pollOnce+100) (BuildId: buildid)
A/DEBUG:       #51 pc 0000000000349674  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #52 pc 0000000000347c9c  /data/app/com.myapp/lib/arm64/libflutter.so (BuildId: buildid)
A/DEBUG:       #53 pc 00000000000c14dc  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: buildid)
A/DEBUG:       #54 pc 0000000000054930  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: buildid)
E/tombstoned: Tombstone written to: tombstone_22
```
</details>

**Comment by renefloor** [comment]
I just published PR #773 as cached_network_image: ^3.2.2
I've made a release apk of the example app using Flutter 3.3. It doesn't seem to load any images indeed.

**Comment by renefloor** [comment]
Please feel free to re-open the issue if you still encounter that crash with the latest version.

**Comment by josh-burton** [comment]
Unfortunately this didn't fix the crash I'm seeing. It must be unrelated to the immutable buffer changes.

I'm trying to isolate a reproducible sample.

**Comment by josh-burton** [comment]
https://github.com/flutter/flutter/issues/110715
