### ISSUE TITLE
Deprecated API usage: The webOnlyInstantiateImageCodecFromUrl API is deprecated and will be removed in a future release. Please use `createImageCodecFromUrl` from `dart:ui_web` instead.

### ISSUE THREAD

**Issue by alirizadagli** [Baseflow/flutter_cached_network_image#906]
## 🐛 Bug Report

While debugging on Chrome, I get a deprecated warning: `The webOnlyInstantiateImageCodecFromUrl API is deprecated and will be removed in a future release. Please use 'createImageCodecFromUrl' from 'dart:ui_web' instead.`

**Version:** 3.3.0

**Platform:** 
- [ ] :web: Chrome

**Comment by mvanbeusekom** [comment]
Resolved in version 1.2.0 of the cached_network_image_web packages.

**Comment by Sun3** [comment]
I am still getting the same error with cached_network_image: ^3.3.1

**Comment by mvanbeusekom** [comment]
Please check your pubspec.lock file for the `cache_network_image_web` package. It should be version 1.2.0.

If it is not run `flutter pub upgrade`. Resolve any problems if Flutter reports upgrade is not possible.

**Comment by Sun3** [comment]
That was it... thanks.

**Comment by anmol-me** [comment]
The error gets fixed with `cached_network_image` **v3.4.0**.
